
include: "rules/00_common.smk"
include: "rules/01_1kgp.smk"
include: "rules/02_assocs.smk"
#include: "rules/03_data_extractions.smk"

rule all:
    input:

###############
# 00_common.smk
###############

#        config["trait_ids_file"],

###############
# 01_1kgp.smk
###############

## download_1KG_38_annotated        
#        expand(os.path.join(config["working_dir"], "vcfs/1kg/20150319/chrs/{chr}.vcf{gz_ext}"),
#            chr = CHRS,
#            gz_ext = GZ_EXTS),
## fix_vcf_headers
#        expand(os.path.join(config["working_dir"], "vcfs/1kg/20150319/reheaded/{chr}.vcf.gz"),
#            chr = CHRS),
## get_population_file
#        config["local_pop_file"],
## get_population_file_plink
#        config["local_pop_file_plink"],

###############
# 02_assocs.smk
###############

# get associations
        expand("data/gwasrapidd/{date}/associations_raw/{efo_id}.rds",
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS
        ),
# get studies
        expand("data/gwasrapidd/{date}/studies_key/{efo_id}.rds",
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS
        ),
        expand("data/gwasrapidd/{date}/studies_raw/{efo_id}.rds",
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS
        ),
# get_snp_ids
        expand("data/gwasrapidd/{date}/associations_snp_ids/{efo_id}.txt",
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS
        ),
# extract_gtypes
        expand(os.path.join(config["working_dir"], "vcfs/1kg/20150319/filtered/{date}/{efo_id}/by_chr/{chr}.vcf.gz"),
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS,
            chr = CHRS
        ),
# merge_gtypes
        expand("data/gwasrapidd/{date}/vcfs/{efo_id}.vcf.gz",
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS
        ),

###############
# 03_data_extraction.smk
###############

# get_fst
        expand("data/gwasrapidd/{date}/pegas/fst/fst.rds",
            date = DATE_OF_COLLECTION
        ),
# clump_snps
        expand("data/gwasrapidd/{date}/plink/clumped/{efo_id}.clumped",
            date = DATE_OF_COLLECTION,
            efo_id = EFO_IDS)



